import json
from typing import Optional
from litellm import completion
from pydantic import BaseModel, Field

# 复用你现有的数据结构
from ...base_types import StandardContextModel, StandardContext, PlanResult, format_context_str, coupled_plan_to_plan_result
from .coupled_plan_generator import CoupledDecomposition, SubModelPlan
from ...utils import get_content_strict

# ==============================================================================
# Refiner Prompt: 强调“最小修改”和“约束性”
# ==============================================================================
REFINER_PROMPT = """
## [Task]
You are a **DEVS Plan Repair Specialist**.
You are provided with a Draft Decomposition Plan that contains specific defects.
Your ONLY goal is to apply the [Correction Orders] to fix the defects, while preserving the rest of the plan EXACTLY as it is.

## [Input Data]
1. **The Draft Plan**: The current JSON structure (contains defects).
2. **Correction Orders**: The specific instructions on what to fix.
3. **Reference Specs**: The Parent Spec and System Context (Look up definitions here).

## [Operating Rules]
### 1. Conservation Law (CRITICAL)
- **Do NOT Rewrite**: Do not rephrase descriptions, rename models, or change logic UNLESS specifically targeted by the Correction Orders.
- **Copy-Paste Default**: For 90% of the plan, you are just a copy machine. Preserve the existing structure word-for-word.

### 2. Surgical Precision
- Locate the specific Child Model or Coupling Line mentioned in the [Correction Orders].
- Modify ONLY that specific part.

### 3. Cascading Integrity
- When you modify a field, you MUST update its **dependent fields** to maintain logical consistency. For example, If you are ordered to define a schema for a `dict` port, ensure you write a valid text description in the `structure` field, details the structure. 

---

## [Draft Plan]
{old_plan_json}

## [Correction Orders]
(Execute these changes. Be smart: update dependent fields.)
{feedback_instruction}

## [Parent Model Specification]
{spec}

## [System Context]
{context_str}
"""

class CoupledPlanRefiner:
    def __init__(self, model_id: str = "gpt-4o"):
        self.model_id = model_id

    def forward(
        self, 
        old_plan: PlanResult,
        context: StandardContext, 
        feedback_instruction: str,
        guiding_feedback: str = ""
    ) -> CoupledDecomposition:
        """
        Args:
            old_plan: The plan generated by CoupledSplitter (or previous Refiner).
            model_info: The parent model info (same as Splitter).
            context: The system context (same as Splitter).
            feedback_instruction: The specific fix command from the Inspector/Arbiter.
        """
        
        # 1. 序列化旧方案 (作为 Input Anchor)
        old_plan_json = CoupledDecomposition(
            children_plan=[SubModelPlan(
                name=i.class_name,
                specification=i.specification,
            ) for i in old_plan.children_plan],
            coupling_specification=old_plan.coupling_specification or "N/A"
        ).model_dump_json()
        
        # 2. 格式化上下文 (辅助信息)
        context_str = format_context_str(
            context=context,
            use_function=True, 
            use_ports=True,
            use_parent=True, 
            use_siblings=True
        )

        # 3. 构建 Prompt
        prompt = REFINER_PROMPT.format(
            name=old_plan.model_info.class_name,
            old_plan_json=old_plan_json,
            feedback_instruction=feedback_instruction,
            spec=old_plan.model_info.specification.model_dump_json(),
            context_str=context_str,
            guiding_feedback=guiding_feedback if guiding_feedback else "None."
        )

        try:
            # 4. 调用 LLM 
            response = completion(
                model=self.model_id,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.05, # 保证稳定性
                response_format=CoupledDecomposition,
            )
            
            result = get_content_strict(response)
            return CoupledDecomposition.model_validate_json(result)

        except Exception as e:
            # Refiner 失败通常意味着模型无法理解如何修改 JSON，或者修改指令太模糊
            # 此时抛出异常，外层逻辑可以捕获并决定是否回退到 Splitter 重做
            print(f"[Refiner Error] {e}")
            raise e
        
    def forward_to_plan(
        self, 
        old_plan: PlanResult,
        context: StandardContext, 
        feedback_instruction: str,
        guiding_feedback: str = ""
    ) -> PlanResult:
        result = self.forward(
            old_plan=old_plan,
            context=context,
            feedback_instruction=feedback_instruction,
            guiding_feedback=guiding_feedback
        )
        return coupled_plan_to_plan_result(result, old_plan.model_info)